name: Terraform Automation with Destroy
 
on:
  workflow_dispatch: 
  
 
jobs:
  terraform:
    runs-on: ubuntu-latest
 
    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3
 
      # Step 2: Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0  # Specify the Terraform version you need

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.SECRET_KEY }}
          aws-region: us-east-1
 
      # Step 3: Terraform Init
      - name: Terraform Init
        run: terraform init
 
      # Step 4: Terraform Plan
      - name: Terraform Plan
        run: terraform plan
        
 
      # Step 5: Terraform Apply
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'  # Only apply for pushes to 'main'
        run: terraform apply -auto-approve
        
      # Step 6: Terraform Destroy (Manual Trigger)
      - name: Terraform Destroy
        if: github.event_name == 'workflow_dispatch'  # Run only on manual trigger
        run: terraform destroy -auto-approve
       
