name: Terraform integration with Ansible
 
on:
  workflow_dispatch: 

jobs:
  terraform:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.SECRET_KEY }}
          aws-region: us-east-1

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2.0.3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan
        

      - name: Terraform Apply
        run: terraform apply -auto-approve

     

      - name: Save private key to file
        run: |
          echo "$(terraform output -raw private_key)" > private-key.pem
          chmod 600 private-key.pem

      - name: Set up Ansible
        run: sudo apt-get install -y ansible

      - name: Install SSH key for Ansible
        run: |
          mkdir -p ~/.ssh
          echo "$(terraform output -raw private_key)" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "$(terraform output -raw instance_public_ip)"

      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i "$(terraform output -raw instance_public_ip)," setup_web_server.yml
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
